version: "2"
services:
  app:
    container_name: node_app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: # For persistence storage
      - ./data:/data/db
    ports:
      - "27017:27017"