version: "2"
services:
  app:
    environment:
      MONGO_URL: mongodb://mongo/pictures
      PORT: 3000
      VIRTUAL_HOST: apod.local
    restart: always
    build: .
    ports:
      - 3000
    networks:
      - proxy
      - database
    volumes:
      - ./:/usr/src/app
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    networks:
      - database
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

# Isolate the networks (proxy can't see db)
networks:
  proxy:
  database:

# Noeuds extérieurs pour la docker stack
#networks:
#  proxy:
#    external:
#      name: dev_proxy
#  database:
#    external:
#      name: dev_database

# Save data file directly in docker volume
volumes:
  mongo: